# Docker Compose for local testing before Render deployment
# This mimics the static file serving that Render provides

services:
  # Static file server using NGINX (similar to Render's CDN)
  static-server:
    image: nginx:alpine
    container_name: victor-harbour-static
    ports:
      - "8082:80"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Simple Python server (alternative)
  python-server:
    image: python:3.11-alpine
    container_name: victor-harbour-python
    working_dir: /app
    volumes:
      - .:/app:ro
    ports:
      - "8082:8000"
    command: python -m http.server 8000
    restart: unless-stopped
    profiles:
      - python  # Only start with: docker compose --profile python up

networks:
  default:
    name: victor-harbour-network