version: '3.8'

services:
  # Local development server using NGINX
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      # Mount current directory for live reloading during development
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./assets:/usr/share/nginx/html/assets:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    
  # Alternative: Simple HTTP server using Python
  python-server:
    image: python:3.11-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8082:8000"
    command: python -m http.server 8000
    profiles:
      - python
    restart: unless-stopped

# Networks (optional)
networks:
  default:
    name: victor-harbor-network